### PR TITLE
Feature/anc dataprovider

### PR DESCRIPTION
**Pull request by kolyaratishin**
Add completed Anc dataprovider

### CODE REVIEW

**Comment by Oleksandr-Eleks** [comment]
Please see my comments from here: https://github.com/Oleksandr-Eleks/pharmagator/pull/34#pullrequestreview-796620086

**Review by Oleksandr-Eleks — COMMENTED** [review]
Please do fixes according to comments in closed PR

**Comment by kolyaratishin** [comment]
> Please do fixes according to comments in closed PR

Done

**Review by Oleksandr-Eleks — APPROVED** [review]

**Comment by kolyaratishin** [comment]
Merged

**Pull request merged**
